# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: daily
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright*"

      minor:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major

    ignore:
      # keep this in sync with .node-version file, if we e.g. use node 20, we do not want to update the types to latest 22
      - dependency-name: "@types/node"
        update-types: [version-update:semver-major]

      # TODO: remove when https://github.com/vuejs/repl/issues/269 is fixed
      - dependency-name: "@vue/repl"
        update-types: [version-update:semver-minor]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/demo-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/playground
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/showcase
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/chartjs-plugin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/eslint-plugin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/figma-plugin-sync-icons
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/figma-utils
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/flags
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/github-metrics
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/headless
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/icons
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt-docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt-docs/playground
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt/playground
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt/tests/fixtures/basic
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nuxt/tests/fixtures/i18n
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/playwright-utils
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/shared
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/sit-onyx
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/storybook-utils
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/vite-plugin-svg
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/vitepress-theme
    schedule:
      interval: daily
